name: reinventerlabs
favicon: null
layout_spectrum: 0.9758616359904408
typography_spectrum: 0.9108560492750257
title: Reinventer Labs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#85c225'
    - '#0093dd'
    - '#251f1d'
    - '#847f7e'
  brandStrength: 0.7658842576202005
  lightness: 0.8711997687350959
  saturation: 0.6817137291654944
  rhythmicContrast: 0.32060752902179956
purpose: []
